person = {'name':'param', 'age':19 , 'gender' : 'Male' , 'email': 'email@gmail.com'}
update_person = {'name':'Param patel' , 'email':'iamparam102@gmail.com' , 'hobbie':'hockey'}
# person.clear()
print(person)
data = person.copy()
print(data)
data = person.items()
print(data)
data = person.keys()
print(data)
data = person.values()
print(data)
data = person.pop('age')
print(data)
print(person)
data = person.popitem()
print(data)
print(person)
person.update(update_person)
print(person   )