colors = [ 'red' , 'blue' , 'green' , 'yellow','yellow' , 11 , True , 10.10 ]
vegitables = [ 'tomato' , 'potato' , 'ladis finger' , 'carrot']
numbers = [10,20,30,40,50,60,70]
colors.append('black')
print(colors)
colors.extend(numbers)
print(colors)
colors.insert(4,'white')
print(colors)
colors.remove(True)
print(colors)
answer = colors.pop(6)
print(colors)
print(answer)
numbers.clear()
print(numbers)
index = colors.index('black')
print(index)
count = colors.count('yellow')
print(count)
vegitables.sort()
print(vegitables)
vegitables.reverse()
print(vegitables)
copy_list = colors.copy()
print(copy_list)